//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace Utg.Api.Models.TrxModels.TrXCreditResponse
{

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class Message
    {

        private Authentication authenticationField;

        private Response responseField;

        private string signatureField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Authentication Authentication
        {
            get
            {
                return this.authenticationField;
            }
            set
            {
                this.authenticationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Response Response
        {
            get
            {
                return this.responseField;
            }
            set
            {
                this.responseField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Signature
        {
            get
            {
                return this.signatureField;
            }
            set
            {
                this.signatureField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Authentication
    {

        private uint clientField;

        private string sourceField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public uint Client
        {
            get
            {
                return this.clientField;
            }
            set
            {
                this.clientField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Source
        {
            get
            {
                return this.sourceField;
            }
            set
            {
                this.sourceField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Echo
    {

        private System.Xml.XmlElement[] anyField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Row
    {

        private uint clientField;

        private string dbaField;

        private string guidField;

        private TransType tranTypeField;

        private bool tranTypeFieldSpecified;

        private TransAction tranActionField;

        private bool tranActionFieldSpecified;

        private string responseCodeField;

        private string responseTextField;

        private string debugInfoField;

        private string firstNameField;

        private string lastNameField;

        private string userNameField;

        private decimal amountField;

        private bool amountFieldSpecified;

        private decimal approvedAmountField;

        private bool approvedAmountFieldSpecified;

        private uint binField;

        private bool binFieldSpecified;

        private uint lastFourField;

        private bool lastFourFieldSpecified;

        private CardNameType cardTypeField;

        private bool cardTypeFieldSpecified;

        private string tranDateField;

        private string tranTimeField;

        private string voidGuidField;

        private string captureGuidField;

        private string returnGuidField;

        private string reversalGuidField;

        private string storageSafeGuidField;

        private string recurringGuidField;

        private BatchStatusType statusField;

        private bool statusFieldSpecified;

        private ushort stagingField;

        private bool stagingFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public uint Client
        {
            get
            {
                return this.clientField;
            }
            set
            {
                this.clientField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Dba
        {
            get
            {
                return this.dbaField;
            }
            set
            {
                this.dbaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Guid
        {
            get
            {
                return this.guidField;
            }
            set
            {
                this.guidField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TransType TranType
        {
            get
            {
                return this.tranTypeField;
            }
            set
            {
                this.tranTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TranTypeSpecified
        {
            get
            {
                return this.tranTypeFieldSpecified;
            }
            set
            {
                this.tranTypeFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TransAction TranAction
        {
            get
            {
                return this.tranActionField;
            }
            set
            {
                this.tranActionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TranActionSpecified
        {
            get
            {
                return this.tranActionFieldSpecified;
            }
            set
            {
                this.tranActionFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ResponseCode
        {
            get
            {
                return this.responseCodeField;
            }
            set
            {
                this.responseCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ResponseText
        {
            get
            {
                return this.responseTextField;
            }
            set
            {
                this.responseTextField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DebugInfo
        {
            get
            {
                return this.debugInfoField;
            }
            set
            {
                this.debugInfoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FirstName
        {
            get
            {
                return this.firstNameField;
            }
            set
            {
                this.firstNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LastName
        {
            get
            {
                return this.lastNameField;
            }
            set
            {
                this.lastNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string UserName
        {
            get
            {
                return this.userNameField;
            }
            set
            {
                this.userNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal Amount
        {
            get
            {
                return this.amountField;
            }
            set
            {
                this.amountField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AmountSpecified
        {
            get
            {
                return this.amountFieldSpecified;
            }
            set
            {
                this.amountFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal ApprovedAmount
        {
            get
            {
                return this.approvedAmountField;
            }
            set
            {
                this.approvedAmountField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ApprovedAmountSpecified
        {
            get
            {
                return this.approvedAmountFieldSpecified;
            }
            set
            {
                this.approvedAmountFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public uint Bin
        {
            get
            {
                return this.binField;
            }
            set
            {
                this.binField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BinSpecified
        {
            get
            {
                return this.binFieldSpecified;
            }
            set
            {
                this.binFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public uint LastFour
        {
            get
            {
                return this.lastFourField;
            }
            set
            {
                this.lastFourField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LastFourSpecified
        {
            get
            {
                return this.lastFourFieldSpecified;
            }
            set
            {
                this.lastFourFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CardNameType CardType
        {
            get
            {
                return this.cardTypeField;
            }
            set
            {
                this.cardTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CardTypeSpecified
        {
            get
            {
                return this.cardTypeFieldSpecified;
            }
            set
            {
                this.cardTypeFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TranDate
        {
            get
            {
                return this.tranDateField;
            }
            set
            {
                this.tranDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TranTime
        {
            get
            {
                return this.tranTimeField;
            }
            set
            {
                this.tranTimeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string VoidGuid
        {
            get
            {
                return this.voidGuidField;
            }
            set
            {
                this.voidGuidField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CaptureGuid
        {
            get
            {
                return this.captureGuidField;
            }
            set
            {
                this.captureGuidField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ReturnGuid
        {
            get
            {
                return this.returnGuidField;
            }
            set
            {
                this.returnGuidField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ReversalGuid
        {
            get
            {
                return this.reversalGuidField;
            }
            set
            {
                this.reversalGuidField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string StorageSafeGuid
        {
            get
            {
                return this.storageSafeGuidField;
            }
            set
            {
                this.storageSafeGuidField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RecurringGuid
        {
            get
            {
                return this.recurringGuidField;
            }
            set
            {
                this.recurringGuidField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public BatchStatusType Status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StatusSpecified
        {
            get
            {
                return this.statusFieldSpecified;
            }
            set
            {
                this.statusFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ushort Staging
        {
            get
            {
                return this.stagingField;
            }
            set
            {
                this.stagingField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StagingSpecified
        {
            get
            {
                return this.stagingFieldSpecified;
            }
            set
            {
                this.stagingFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    public enum TransType
    {

        /// <remarks/>
        Account,

        /// <remarks/>
        Ach,

        /// <remarks/>
        Address,

        /// <remarks/>
        Alert,

        /// <remarks/>
        Amex,

        /// <remarks/>
        Application,

        /// <remarks/>
        Bank,

        /// <remarks/>
        Batch,

        /// <remarks/>
        Cash,

        /// <remarks/>
        Client,

        /// <remarks/>
        Credit,

        /// <remarks/>
        CriminalRecord,

        /// <remarks/>
        Debit,

        /// <remarks/>
        Ebt,

        /// <remarks/>
        eSignature,

        /// <remarks/>
        File,

        /// <remarks/>
        GiftCard,

        /// <remarks/>
        GeoIp,

        /// <remarks/>
        Guid,

        /// <remarks/>
        Invoice,

        /// <remarks/>
        Interchange,

        /// <remarks/>
        Lead,

        /// <remarks/>
        Ledger,

        /// <remarks/>
        Log,

        /// <remarks/>
        Match,

        /// <remarks/>
        Nacha,

        /// <remarks/>
        NegativeDB,

        /// <remarks/>
        Network,

        /// <remarks/>
        Note,

        /// <remarks/>
        Obscure,

        /// <remarks/>
        Ofac,

        /// <remarks/>
        OutOfWallet,

        /// <remarks/>
        Preference,

        /// <remarks/>
        PayPage,

        /// <remarks/>
        Pci,

        /// <remarks/>
        Pricing,

        /// <remarks/>
        Recurring,

        /// <remarks/>
        Residual,

        /// <remarks/>
        Rights,

        /// <remarks/>
        Rule,

        /// <remarks/>
        Score,

        /// <remarks/>
        Setting,

        /// <remarks/>
        Stat,

        /// <remarks/>
        Statement,

        /// <remarks/>
        StorageSafe,

        /// <remarks/>
        SysLog,

        /// <remarks/>
        Template,

        /// <remarks/>
        Terminal,

        /// <remarks/>
        TerminalGroup,

        /// <remarks/>
        Ticket,

        /// <remarks/>
        TinMatch,

        /// <remarks/>
        Tsys,

        /// <remarks/>
        User,

        /// <remarks/>
        VantageScore,

        /// <remarks/>
        Velocity,

        /// <remarks/>
        VeriFone,

        /// <remarks/>
        Vmpi,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    public enum TransAction
    {

        /// <remarks/>
        Activate,

        /// <remarks/>
        Append,

        /// <remarks/>
        Approve,

        /// <remarks/>
        Auth,

        /// <remarks/>
        Avs,

        /// <remarks/>
        Balance,

        /// <remarks/>
        Cancel,

        /// <remarks/>
        Capture,

        /// <remarks/>
        CashAdvance,

        /// <remarks/>
        Clone,

        /// <remarks/>
        Close,

        /// <remarks/>
        Decline,

        /// <remarks/>
        Decrypt,

        /// <remarks/>
        Delete,

        /// <remarks/>
        Download,

        /// <remarks/>
        Encrypt,

        /// <remarks/>
        Forecast,

        /// <remarks/>
        Force,

        /// <remarks/>
        Hierarchy,

        /// <remarks/>
        Inquiry,

        /// <remarks/>
        Insert,

        /// <remarks/>
        KeepAlive,

        /// <remarks/>
        Logoff,

        /// <remarks/>
        Logon,

        /// <remarks/>
        Lookup,

        /// <remarks/>
        Notification,

        /// <remarks/>
        Prenote,

        /// <remarks/>
        Publish,

        /// <remarks/>
        Ping,

        /// <remarks/>
        QuasiCash,

        /// <remarks/>
        Query,

        /// <remarks/>
        Refund,

        /// <remarks/>
        Report,

        /// <remarks/>
        Release,

        /// <remarks/>
        Resend,

        /// <remarks/>
        Reset,

        /// <remarks/>
        Response,

        /// <remarks/>
        Return,

        /// <remarks/>
        Reversal,

        /// <remarks/>
        Sale,

        /// <remarks/>
        Security,

        /// <remarks/>
        Send,

        /// <remarks/>
        Settle,

        /// <remarks/>
        Startup,

        /// <remarks/>
        Status,

        /// <remarks/>
        Update,

        /// <remarks/>
        Void,

        /// <remarks/>
        Withdrawal,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    public enum BatchStatusType
    {

        /// <remarks/>
        Open,

        /// <remarks/>
        Closed,

        /// <remarks/>
        Settled,

        /// <remarks/>
        Hold,

        /// <remarks/>
        Released,
    }



    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Duplicate
    {

        private string guidField;

        private decimal amountField;

        private string approvalCodeField;

        private CardNameType accountBrandField;

        private string purchaseIdField;

        private SurchargeMethodType calculationMethodField;

        private bool calculationMethodFieldSpecified;

        private decimal surchargeAmountField;

        private bool surchargeAmountFieldSpecified;

        private decimal percentField;

        private bool percentFieldSpecified;

        private decimal tipAmountField;

        private bool tipAmountFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Guid
        {
            get
            {
                return this.guidField;
            }
            set
            {
                this.guidField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal Amount
        {
            get
            {
                return this.amountField;
            }
            set
            {
                this.amountField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ApprovalCode
        {
            get
            {
                return this.approvalCodeField;
            }
            set
            {
                this.approvalCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CardNameType AccountBrand
        {
            get
            {
                return this.accountBrandField;
            }
            set
            {
                this.accountBrandField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PurchaseId
        {
            get
            {
                return this.purchaseIdField;
            }
            set
            {
                this.purchaseIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SurchargeMethodType CalculationMethod
        {
            get
            {
                return this.calculationMethodField;
            }
            set
            {
                this.calculationMethodField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CalculationMethodSpecified
        {
            get
            {
                return this.calculationMethodFieldSpecified;
            }
            set
            {
                this.calculationMethodFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal SurchargeAmount
        {
            get
            {
                return this.surchargeAmountField;
            }
            set
            {
                this.surchargeAmountField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SurchargeAmountSpecified
        {
            get
            {
                return this.surchargeAmountFieldSpecified;
            }
            set
            {
                this.surchargeAmountFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal Percent
        {
            get
            {
                return this.percentField;
            }
            set
            {
                this.percentField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PercentSpecified
        {
            get
            {
                return this.percentFieldSpecified;
            }
            set
            {
                this.percentFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal TipAmount
        {
            get
            {
                return this.tipAmountField;
            }
            set
            {
                this.tipAmountField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TipAmountSpecified
        {
            get
            {
                return this.tipAmountFieldSpecified;
            }
            set
            {
                this.tipAmountFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    public enum CardNameType
    {

        /// <remarks/>
        All,

        /// <remarks/>
        Ach,

        /// <remarks/>
        Amex,

        /// <remarks/>
        Discover,

        /// <remarks/>
        Ebt,

        /// <remarks/>
        Jcb,

        /// <remarks/>
        MasterCard,

        /// <remarks/>
        Visa,

        /// <remarks/>
        Unknown,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    public enum SurchargeMethodType
    {

        /// <remarks/>
        Fixed,

        /// <remarks/>
        Percent,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Recurring
    {

        private string guidField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Guid
        {
            get
            {
                return this.guidField;
            }
            set
            {
                this.guidField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UserDefined
    {

        private string guidField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Guid
        {
            get
            {
                return this.guidField;
            }
            set
            {
                this.guidField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Shipping
    {

        private string guidField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Guid
        {
            get
            {
                return this.guidField;
            }
            set
            {
                this.guidField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Account
    {

        private string guidField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Guid
        {
            get
            {
                return this.guidField;
            }
            set
            {
                this.guidField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class StorageSafe
    {

        private string guidField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Guid
        {
            get
            {
                return this.guidField;
            }
            set
            {
                this.guidField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Surcharge
    {

        private SurchargeMethodType calculationMethodField;

        private decimal percentField;

        private bool percentFieldSpecified;

        private decimal amountField;

        private bool amountFieldSpecified;

        private decimal surchargeAmountField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SurchargeMethodType CalculationMethod
        {
            get
            {
                return this.calculationMethodField;
            }
            set
            {
                this.calculationMethodField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal Percent
        {
            get
            {
                return this.percentField;
            }
            set
            {
                this.percentField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PercentSpecified
        {
            get
            {
                return this.percentFieldSpecified;
            }
            set
            {
                this.percentFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal Amount
        {
            get
            {
                return this.amountField;
            }
            set
            {
                this.amountField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AmountSpecified
        {
            get
            {
                return this.amountFieldSpecified;
            }
            set
            {
                this.amountFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal SurchargeAmount
        {
            get
            {
                return this.surchargeAmountField;
            }
            set
            {
                this.surchargeAmountField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RuleResult
    {

        private string[] guidField;

        private string[] responseCodeField;

        private string[] descriptionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Guid", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] Guid
        {
            get
            {
                return this.guidField;
            }
            set
            {
                this.guidField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ResponseCode", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] ResponseCode
        {
            get
            {
                return this.responseCodeField;
            }
            set
            {
                this.responseCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Description", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Result
    {

        private string responseCodeField;

        private string responseTextField;

        private string debugInfoField;

        private decimal approvedAmountField;

        private bool approvedAmountFieldSpecified;

        private string avsResultField;

        private string cvvResultField;

        private string cavvResultField;

        private string approvalCodeField;

        private string commercialResultField;

        private string nameVerificationResultField;

        private string phoneVerificationResultField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ResponseCode
        {
            get
            {
                return this.responseCodeField;
            }
            set
            {
                this.responseCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ResponseText
        {
            get
            {
                return this.responseTextField;
            }
            set
            {
                this.responseTextField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DebugInfo
        {
            get
            {
                return this.debugInfoField;
            }
            set
            {
                this.debugInfoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal ApprovedAmount
        {
            get
            {
                return this.approvedAmountField;
            }
            set
            {
                this.approvedAmountField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ApprovedAmountSpecified
        {
            get
            {
                return this.approvedAmountFieldSpecified;
            }
            set
            {
                this.approvedAmountFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AvsResult
        {
            get
            {
                return this.avsResultField;
            }
            set
            {
                this.avsResultField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CvvResult
        {
            get
            {
                return this.cvvResultField;
            }
            set
            {
                this.cvvResultField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CavvResult
        {
            get
            {
                return this.cavvResultField;
            }
            set
            {
                this.cavvResultField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ApprovalCode
        {
            get
            {
                return this.approvalCodeField;
            }
            set
            {
                this.approvalCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CommercialResult
        {
            get
            {
                return this.commercialResultField;
            }
            set
            {
                this.commercialResultField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NameVerificationResult
        {
            get
            {
                return this.nameVerificationResultField;
            }
            set
            {
                this.nameVerificationResultField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PhoneVerificationResult
        {
            get
            {
                return this.phoneVerificationResultField;
            }
            set
            {
                this.phoneVerificationResultField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Reference
    {

        private string guidField;

        private string tranDateField;

        private string tranTimeField;

        private uint stanField;

        private bool stanFieldSpecified;

        private string purchaseIdField;

        private CardNameType accountBrandField;

        private bool accountBrandFieldSpecified;

        private uint lastFourField;

        private bool lastFourFieldSpecified;

        private string parField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Guid
        {
            get
            {
                return this.guidField;
            }
            set
            {
                this.guidField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TranDate
        {
            get
            {
                return this.tranDateField;
            }
            set
            {
                this.tranDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TranTime
        {
            get
            {
                return this.tranTimeField;
            }
            set
            {
                this.tranTimeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public uint Stan
        {
            get
            {
                return this.stanField;
            }
            set
            {
                this.stanField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StanSpecified
        {
            get
            {
                return this.stanFieldSpecified;
            }
            set
            {
                this.stanFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PurchaseId
        {
            get
            {
                return this.purchaseIdField;
            }
            set
            {
                this.purchaseIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CardNameType AccountBrand
        {
            get
            {
                return this.accountBrandField;
            }
            set
            {
                this.accountBrandField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AccountBrandSpecified
        {
            get
            {
                return this.accountBrandFieldSpecified;
            }
            set
            {
                this.accountBrandFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public uint LastFour
        {
            get
            {
                return this.lastFourField;
            }
            set
            {
                this.lastFourField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LastFourSpecified
        {
            get
            {
                return this.lastFourFieldSpecified;
            }
            set
            {
                this.lastFourFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Par
        {
            get
            {
                return this.parField;
            }
            set
            {
                this.parField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Response
    {

        private Reference referenceField;

        private Result resultField;

        private RuleResult ruleResultField;

        private Surcharge surchargeField;

        private StorageSafe storageSafeField;

        private Account accountField;

        private Shipping shippingField;

        private UserDefined userDefinedField;

        private Recurring recurringField;

        private Duplicate duplicateField;

        private string[] smartCardField;

        private Echo echoField;

        private Row[] queryResponseField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Reference Reference
        {
            get
            {
                return this.referenceField;
            }
            set
            {
                this.referenceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Result Result
        {
            get
            {
                return this.resultField;
            }
            set
            {
                this.resultField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public RuleResult RuleResult
        {
            get
            {
                return this.ruleResultField;
            }
            set
            {
                this.ruleResultField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Surcharge Surcharge
        {
            get
            {
                return this.surchargeField;
            }
            set
            {
                this.surchargeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public StorageSafe StorageSafe
        {
            get
            {
                return this.storageSafeField;
            }
            set
            {
                this.storageSafeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Account Account
        {
            get
            {
                return this.accountField;
            }
            set
            {
                this.accountField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Shipping Shipping
        {
            get
            {
                return this.shippingField;
            }
            set
            {
                this.shippingField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public UserDefined UserDefined
        {
            get
            {
                return this.userDefinedField;
            }
            set
            {
                this.userDefinedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Recurring Recurring
        {
            get
            {
                return this.recurringField;
            }
            set
            {
                this.recurringField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Duplicate Duplicate
        {
            get
            {
                return this.duplicateField;
            }
            set
            {
                this.duplicateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Tag", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public string[] SmartCard
        {
            get
            {
                return this.smartCardField;
            }
            set
            {
                this.smartCardField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Echo Echo
        {
            get
            {
                return this.echoField;
            }
            set
            {
                this.echoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public Row[] QueryResponse
        {
            get
            {
                return this.queryResponseField;
            }
            set
            {
                this.queryResponseField = value;
            }
        }
    }
}